### ISSUE TITLE
Issues in Flatsome Theme

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/wallet-system-for-woocommerce#25]
Bug Name - Issues in flatsome theme
Area Path - Frontend
Status - New
Woo Commerce Version - 5.5.2
WordPress Version - 5.8
PHP Version - 8.0.0
Plugin Version - 2.1.0

1. Description - Wallet balance amount is not visible
![w8](https://user-images.githubusercontent.com/86114080/129199251-19783999-1872-4381-832b-3564a8057f76.png)

2. Description - Designing issue 
![w14](https://user-images.githubusercontent.com/86114080/129199955-8591b935-aa1f-45c7-b7c3-b95e2639a0ba.png)
![w20](https://user-images.githubusercontent.com/86114080/129309370-9b220098-71f9-4d15-add9-ef53b52d94ad.png)

3. Responsiveness issue
![w11](https://user-images.githubusercontent.com/86114080/129200107-764331b6-8f86-4fb5-8068-568550f005f3.png)

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/129680711-8e384965-9c1d-46ac-8893-277c83f0f5cc.png)
solved

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/129681188-3cef0671-1f73-4fca-90c0-e4493166cf69.png)

**Comment by shrishti-mwb** [comment]
Done
