### ISSUE TITLE
Short code is not working well in shop page

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/wallet-system-for-woocommerce#30]
Bug Name -Short code is not working well in shop page
Area Path - frontend
Status - New
Woo Commerce Version - 5.6.0
WordPress Version - 5.8
PHP Version - 8.0.0
Plugin Version - 2.1.0
Description - Tabs available in shop page is not working

**Comment by shobhapatwal-cedcoss** [comment]
fixed the issue

**Comment by shrishti-mwb** [comment]
done
