### ISSUE TITLE
Issue with elementer compatibility 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/wallet-system-for-woocommerce#32]
WP: 5.8
WC: 5.6
Version: 2.1.0
Description: when we are transferring wallet money to ourselves, there should be a warning 
![image](https://user-images.githubusercontent.com/85384857/133615312-c9e7803a-88f2-40e2-87bd-ff258d437e8d.png)

**Comment by shobhapatwal-cedcoss** [comment]
showing message on transferring amount to yourself
![screenshot_194](https://user-images.githubusercontent.com/76722898/133641245-30929f61-6a79-434b-b4dc-aab615b28091.png)

**Comment by Sukirti-CEDCOSS** [comment]
Verified
