### ISSUE TITLE
QA/PHPcs Issue 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/wallet-system-for-woocommerce#34]
DOC:
https://docs.google.com/document/d/1NQSMpuQinNTN-4_O_QB3iWmK13J-X6zb4FoWBcEqs4I/edit?usp=sharing

File:
[PHPcs.zip](https://github.com/Makewebbetter/wallet-system-for-woocommerce/files/7185906/PHPcs.zip)
[wallet-system-for-woocommerce.zip](https://github.com/Makewebbetter/wallet-system-for-woocommerce/files/7185908/wallet-system-for-woocommerce.zip)

**Comment by shobhapatwal-cedcoss** [comment]
resolved

**Comment by Sukirti-CEDCOSS** [comment]
Verified
