### ISSUE TITLE
When we are clicking the arrow beside (Amount) it jumps and is placed beside (transaction)

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/wallet-system-for-woocommerce#37]
Wordpress: 5.8.2
WooCommerce: 5.9.0
Description:
When we are clicking the arrow beside (Amount) it jumps and is placed beside (transaction)
![image](https://user-images.githubusercontent.com/85384857/142582010-0c96dedf-f05d-4482-9fd4-5a47c990c845.png)
![image](https://user-images.githubusercontent.com/85384857/142582056-06f1068d-af99-47d7-abcd-b00ce3fee0cc.png)
![image](https://user-images.githubusercontent.com/85384857/142584124-770e3eed-e82f-4eec-ac39-86f1e9e1baab.png)

**Comment by navneet-cedcoss** [comment]
This is the table functionality

**Comment by Sukirti-CEDCOSS** [comment]
Not an Issue
